01/07/2026

Assignment : 14

Pandas assignment : 5

AI/ML Data Preparation

In [2]:
# Pandas Training - Day 5 Assignment
# Topics: AI/ML Data Preparation

import pandas as pd

# Create Customer DataFrame

data = {
    "Age": [22, 25, 30, 35, 40, 28, 32, 45],
    "Salary": [25000, 30000, 45000, 50000, 60000, 35000, 48000, 70000],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Purchased": [0, 1, 1, 1, 1, 0, 1, 1]
}

df = pd.DataFrame(data)

# Display DataFrame
df

   Age  Salary  Gender  Purchased
0   22   25000    Male          0
1   25   30000  Female          1
2   30   45000    Male          1
3   35   50000  Female          1
4   40   60000    Male          1
5   28   35000  Female          0
6   32   48000    Male          1
7   45   70000  Female          1

In [3]:
# Display first 5 rows

df.head(5)

   Age  Salary  Gender  Purchased
0   22   25000    Male          0
1   25   30000  Female          1
2   30   45000    Male          1
3   35   50000  Female          1
4   40   60000    Male          1

In [4]:
# Display dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        8 non-null      int64
 1   Salary     8 non-null      int64
 2   Gender     8 non-null      object
 3   Purchased  8 non-null      int64
dtypes: int64(3), object(1)
memory usage: 388.0+ bytes

In [5]:
# Display statistical summary

df.describe()

             Age       Salary  Purchased
count   8.000000      8.00000    8.00000
mean   32.125000  45375.00000    0.75000
std     7.661359  15155.73913    0.46291
min    22.000000  25000.00000    0.00000
25%    27.250000  33750.00000    0.75000
50%    31.000000  46500.00000    1.00000
75%    36.250000  52500.00000    1.00000
max    45.000000  70000.00000    1.00000

In [6]:
# Encode Gender column
# Male = 1, Female = 0

df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})

df

   Age  Salary  Gender  Purchased
0   22   25000       1          0
1   25   30000       0          1
2   30   45000       1          1
3   35   50000       0          1
4   40   60000       1          1
5   28   35000       0          0
6   32   48000       1          1
7   45   70000       0          1

In [7]:
# Find correlation between Age and Salary

df["Age"].corr(df["Salary"])

0.9899483184333322

In [8]:
# Select features

X = df[["Age", "Salary", "Gender"]]

# Select target

y = df["Purchased"]

# Display features
X

   Age  Salary  Gender
0   22   25000       1
1   25   30000       0
2   30   45000       1
3   35   50000       0
4   40   60000       1
5   28   35000       0
6   32   48000       1
7   45   70000       0

In [9]:
# Display target

y

0    0
1    1
2    1
3    1
4    1
5    0
6    1
7    1
Name: Purchased, dtype: int64

Questions

Q1. What is Data Exploration?

Data Exploration is the process of understanding and analyzing a dataset before using it for Machine Learning.


    

Q2. What is a Feature in Machine Learning?

A Feature is an input variable used by a Machine Learning model to make predictions.

Example:

Age, Salary, Gender



Q3. What is a Target Variable?

A Target Variable is the output that a Machine Learning model tries to predict.

In this dataset:

Purchased

is the target variable.


    

Q4. What is Correlation?

Correlation shows the relationship between two variables. It tells us how strongly two variables are related.

The correlation value ranges from -1 to +1.

+1 → Strong positive relationship
0 → No linear relationship
-1 → Strong negative relationship

    
    
Q5. Why is Encoding required in Machine Learning?

Encoding is required to convert categorical/text data into numerical values so that Machine Learning algorithms can process the data.

Example:

Male → 1
Female → 0



Q6. What is the difference between Training Data and Testing Data?
Training Data: Used to train the Machine Learning model.
Testing Data: Used to test how well the trained model performs on unseen data.

For example, a dataset can be divided into 80% training data and 20% testing data.