01/07/2026

Assignment : 15

Pandas Mini Project

In [5]:
# Create CSV Dataset

import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],
    "Name": ["Raj", "Amit", "Priya", "Sneha", "Rahul", "Pooja", "Karan", "Neha", "Akash", "Komal", "Vikas", "Riya", "Raj"],
    "Age": [21, 22, 20, 23, 21, 22, 20, 21, 24, 23, None, 22, 21],
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male"],
    "City": ["Pune", "Mumbai", "Nashik", "Pune", "Mumbai", "Pune", "Nashik", "Pune", "Mumbai", "Pune", "Pune", "Mumbai", "Pune"],
    "Course": ["Python", "AI", "Python", "Data Science", "AI", "Python", "Data Science", "AI", "Python", "Data Science", "Python", "AI", "Python"],
    "Attendance": [90, 80, 95, 88, 75, 98, 82, 91, 85, 96, 90, None, 90],
    "Marks": [85, 75, 92, 81, 65, 96, 79, 89, 72, 94, None, 85, 85],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("student_performance.csv", index=False)

print("student_performance.csv created successfully!")

student_performance.csv created successfully!

In [6]:
# Load Dataset

df = pd.read_csv("student_performance.csv")

df

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes
1,102,Amit,22.0,Male,Mumbai,AI,80.0,75.0,No
2,103,Priya,20.0,Female,Nashik,Python,95.0,92.0,Yes
3,104,Sneha,23.0,Female,Pune,Data Science,88.0,81.0,Yes
4,105,Rahul,21.0,Male,Mumbai,AI,75.0,65.0,No
5,106,Pooja,22.0,Female,Pune,Python,98.0,96.0,Yes
6,107,Karan,20.0,Male,Nashik,Data Science,82.0,79.0,No
7,108,Neha,21.0,Female,Pune,AI,91.0,89.0,Yes
8,109,Akash,24.0,Male,Mumbai,Python,85.0,72.0,No
9,110,Komal,23.0,Female,Pune,Data Science,96.0,94.0,Yes
10,111,Vikas,NaN,Male,Pune,Python,90.0,NaN,Yes
11,112,Riya,22.0,Female,Mumbai,AI,NaN,85.0,No
12,113,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes

In [7]:
# First 5 rows
df.head()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes
1,102,Amit,22.0,Male,Mumbai,AI,80.0,75.0,No
2,103,Priya,20.0,Female,Nashik,Python,95.0,92.0,Yes
3,104,Sneha,23.0,Female,Pune,Data Science,88.0,81.0,Yes
4,105,Rahul,21.0,Male,Mumbai,AI,75.0,65.0,No

In [8]:
# Last 5 rows
df.tail()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
8,109,Akash,24.0,Male,Mumbai,Python,85.0,72.0,No
9,110,Komal,23.0,Female,Pune,Data Science,96.0,94.0,Yes
10,111,Vikas,NaN,Male,Pune,Python,90.0,NaN,Yes
11,112,Riya,22.0,Female,Mumbai,AI,NaN,85.0,No
12,113,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes

In [9]:
# Shape
print("Shape:", df.shape)

Shape: (13, 9)

In [10]:
# Column names
print(df.columns)

Index(['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Course', 'Attendance',
       'Marks', 'Purchased'],
      dtype='object')

In [11]:
# Data types
print(df.dtypes)

Student_ID      int64
Name           object
Age           float64
Gender         object
City           object
Course         object
Attendance    float64
Marks         float64
Purchased      object
dtype: object

In [12]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  13 non-null     int64
 1   Name        13 non-null     object
 2   Age         12 non-null     float64
 3   Gender      13 non-null     object
 4   City        13 non-null     object
 5   Course      13 non-null     object
 6   Attendance  12 non-null     float64
 7   Marks       12 non-null     float64
 8   Purchased   13 non-null     object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.0+ KB

In [13]:
# Statistical summary
df.describe()

       Student_ID        Age  Attendance      Marks
count    13.00000  12.000000   12.000000  12.000000
mean    107.00000  21.666667   88.333333  83.166667
std       3.89444   1.230915    6.813534   9.281784
min     101.00000  20.000000   75.000000  65.000000
25%     104.00000  21.000000   84.250000  78.000000
50%     107.00000  21.500000   90.000000  85.000000
75%     110.00000  22.250000   92.000000  89.750000
max     113.00000  24.000000   98.000000  96.000000

In [14]:
# Find missing values
df.isnull()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False,True,False
11,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False

In [15]:
# Count missing values
df.isnull().sum()

Student_ID    0
Name          0
Age           1
Gender        0
City          0
Course        0
Attendance    1
Marks         1
Purchased     0
dtype: int64

In [17]:
# Fill missing Age with average
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill missing Marks with average
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# Fill missing Attendance with average
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())

In [18]:
# Verify missing values
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
City          0
Course        0
Attendance    0
Marks         0
Purchased     0
dtype: int64

In [19]:
# Count duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [20]:
# Remove duplicates
df = df.drop_duplicates()

In [21]:
# Display cleaned dataset
df

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
4,105,Rahul,21.000000,Male,Mumbai,AI,75.000000,65.000000,No
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes

In [22]:
# Name column
df["Name"]

0       Raj
1      Amit
2     Priya
3     Sneha
4     Rahul
5     Pooja
6     Karan
7      Neha
8     Akash
9     Komal
10    Vikas
11     Riya
12      Raj
Name: Name, dtype: object

In [23]:
# Marks column
df["Marks"]

0     85.000000
1     75.000000
2     92.000000
3     81.000000
4     65.000000
5     96.000000
6     79.000000
7     89.000000
8     72.000000
9     94.000000
10    83.166667
11    85.000000
12    85.000000
Name: Marks, dtype: float64

In [24]:
# Name and Marks
df[["Name", "Marks"]]

     Name      Marks
0     Raj  85.000000
1    Amit  75.000000
2   Priya  92.000000
3   Sneha  81.000000
4   Rahul  65.000000
5   Pooja  96.000000
6   Karan  79.000000
7    Neha  89.000000
8   Akash  72.000000
9   Komal  94.000000
10  Vikas  83.166667
11   Riya  85.000000
12    Raj  85.000000

In [26]:
# Name, City and Course
df[["Name", "City", "Course"]]

     Name    City        Course
0     Raj    Pune        Python
1    Amit  Mumbai            AI
2   Priya  Nashik        Python
3   Sneha    Pune  Data Science
4   Rahul  Mumbai            AI
5   Pooja    Pune        Python
6   Karan  Nashik  Data Science
7    Neha    Pune            AI
8   Akash  Mumbai        Python
9   Komal    Pune  Data Science
10  Vikas    Pune        Python
11   Riya  Mumbai            AI
12    Raj    Pune        Python

In [27]:
# Marks greater than 80
df[df["Marks"] > 80]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes

In [28]:
# Marks less than 70
df[df["Marks"] < 70]

   Student_ID   Name   Age Gender    City Course  Attendance  Marks Purchased
4         105  Rahul  21.0   Male  Mumbai     AI        75.0   65.0        No

In [29]:
# Students from Pune
df[df["City"] == "Pune"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes
3,104,Sneha,23.000000,Female,Pune,Data Science,88.0,81.000000,Yes
5,106,Pooja,22.000000,Female,Pune,Python,98.0,96.000000,Yes
7,108,Neha,21.000000,Female,Pune,AI,91.0,89.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.0,94.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.0,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes

In [30]:
# Students from Mumbai
df[df["City"] == "Mumbai"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
1,102,Amit,22.0,Male,Mumbai,AI,80.000000,75.0,No
4,105,Rahul,21.0,Male,Mumbai,AI,75.000000,65.0,No
8,109,Akash,24.0,Male,Mumbai,Python,85.000000,72.0,No
11,112,Riya,22.0,Female,Mumbai,AI,88.333333,85.0,No

In [31]:
# Female students
df[df["Gender"] == "Female"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
2,103,Priya,20.0,Female,Nashik,Python,95.000000,92.0,Yes
3,104,Sneha,23.0,Female,Pune,Data Science,88.000000,81.0,Yes
5,106,Pooja,22.0,Female,Pune,Python,98.000000,96.0,Yes
7,108,Neha,21.0,Female,Pune,AI,91.000000,89.0,Yes
9,110,Komal,23.0,Female,Pune,Data Science,96.000000,94.0,Yes
11,112,Riya,22.0,Female,Mumbai,AI,88.333333,85.0,No

In [32]:
# Male students
df[df["Gender"] == "Male"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes
1,102,Amit,22.000000,Male,Mumbai,AI,80.0,75.000000,No
4,105,Rahul,21.000000,Male,Mumbai,AI,75.0,65.000000,No
6,107,Karan,20.000000,Male,Nashik,Data Science,82.0,79.000000,No
8,109,Akash,24.000000,Male,Mumbai,Python,85.0,72.000000,No
10,111,Vikas,21.666667,Male,Pune,Python,90.0,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes

In [33]:
# AI students
df[df["Course"] == "AI"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
1,102,Amit,22.0,Male,Mumbai,AI,80.000000,75.0,No
4,105,Rahul,21.0,Male,Mumbai,AI,75.000000,65.0,No
7,108,Neha,21.0,Female,Pune,AI,91.000000,89.0,Yes
11,112,Riya,22.0,Female,Mumbai,AI,88.333333,85.0,No

In [34]:
# Python students
df[df["Course"] == "Python"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes
2,103,Priya,20.000000,Female,Nashik,Python,95.0,92.000000,Yes
5,106,Pooja,22.000000,Female,Pune,Python,98.0,96.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.0,72.000000,No
10,111,Vikas,21.666667,Male,Pune,Python,90.0,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes

In [35]:
# Attendance greater than 90
df[df["Attendance"] > 90]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
2,103,Priya,20.0,Female,Nashik,Python,95.0,92.0,Yes
5,106,Pooja,22.0,Female,Pune,Python,98.0,96.0,Yes
7,108,Neha,21.0,Female,Pune,AI,91.0,89.0,Yes
9,110,Komal,23.0,Female,Pune,Data Science,96.0,94.0,Yes

In [36]:
# Marks between 70 and 90
df[df["Marks"].between(70, 90)]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes

In [37]:
# Male students from Pune
df[(df["Gender"] == "Male") & (df["City"] == "Pune")]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.0,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes

In [38]:
# Female students with Marks greater than 85
df[(df["Gender"] == "Female") & (df["Marks"] > 85)]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
2,103,Priya,20.0,Female,Nashik,Python,95.0,92.0,Yes
5,106,Pooja,22.0,Female,Pune,Python,98.0,96.0,Yes
7,108,Neha,21.0,Female,Pune,AI,91.0,89.0,Yes
9,110,Komal,23.0,Female,Pune,Data Science,96.0,94.0,Yes

In [39]:
# Marks ascending
df.sort_values("Marks")

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
4,105,Rahul,21.000000,Male,Mumbai,AI,75.000000,65.000000,No
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes

In [40]:
# Marks descending
df.sort_values("Marks", ascending=False)

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
4,105,Rahul,21.000000,Male,Mumbai,AI,75.000000,65.000000,No

In [41]:
# Attendance highest to lowest
df.sort_values("Attendance", ascending=False)

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
4,105,Rahul,21.000000,Male,Mumbai,AI,75.000000,65.000000,No

In [42]:
# Age lowest to highest
df.sort_values("Age")

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
4,105,Rahul,21.000000,Male,Mumbai,AI,75.000000,65.000000,No
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No

In [43]:
# Unique Cities
df["City"].unique()

array(['Pune', 'Mumbai', 'Nashik'], dtype=object)

In [44]:
# Unique Courses
df["Course"].unique()

array(['Python', 'AI', 'Data Science'], dtype=object)

In [45]:
# Unique Gender values
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [46]:
# Unique Purchased values
df["Purchased"].unique()

array(['Yes', 'No'], dtype=object)

In [47]:
# Students in each City
df["City"].value_counts()

City
Pune      7
Mumbai    4
Nashik    2
Name: count, dtype: int64

In [48]:
# Students in each Course
df["Course"].value_counts()

Course
Python          6
AI              4
Data Science    3
Name: count, dtype: int64

In [49]:
# Male and Female students
df["Gender"].value_counts()

Gender
Male      7
Female    6
Name: count, dtype: int64

In [50]:
# Purchased Yes and No
df["Purchased"].value_counts()

Purchased
Yes    8
No     5
Name: count, dtype: int64

In [51]:
# Average Marks by Course
df.groupby("Course")["Marks"].mean()

Course
AI              78.500000
Data Science    84.666667
Python          85.527778
Name: Marks, dtype: float64

In [52]:
# Average Attendance by Course
df.groupby("Course")["Attendance"].mean()

Course
AI              83.583333
Data Science    88.666667
Python          91.333333
Name: Attendance, dtype: float64

In [53]:
# Total Marks by Course
df.groupby("Course")["Marks"].sum()

Course
AI              314.000000
Data Science    254.000000
Python          513.166667
Name: Marks, dtype: float64

In [54]:
# Maximum Marks by Course
df.groupby("Course")["Marks"].max()

Course
AI              89.0
Data Science    94.0
Python          96.0
Name: Marks, dtype: float64

In [55]:
# Minimum Marks by Course
df.groupby("Course")["Marks"].min()

Course
AI              65.0
Data Science    79.0
Python          72.0
Name: Marks, dtype: float64

In [56]:
# Total Students by Course
df.groupby("Course")["Student_ID"].count()

Course
AI              4
Data Science    3
Python          6
Name: Student_ID, dtype: int64

In [57]:
# Average Marks by Gender
df.groupby("Gender")["Marks"].mean()

Gender
Female    89.500000
Male      77.738095
Name: Marks, dtype: float64

In [58]:
# Average Attendance by City
df.groupby("City")["Attendance"].mean()

City
Mumbai    82.083333
Nashik    88.500000
Pune      91.857143
Name: Attendance, dtype: float64

In [59]:
course_analysis = df.groupby("Course").agg({
    "Marks": ["sum", "mean", "min", "max"],
    "Student_ID": "count"
})

course_analysis

                   Marks                        Student_ID
                     sum       mean   min   max      count
Course
AI            314.000000  78.500000  65.0  89.0          4
Data Science  254.000000  84.666667  79.0  94.0          3
Python        513.166667  85.527778  72.0  96.0          6

In [60]:
# Correlation between numerical columns
df.corr(numeric_only=True)

            Student_ID       Age  Attendance     Marks
Student_ID    1.000000  0.211830    0.192436  0.146079
Age           0.211830  1.000000    0.073467 -0.114050
Attendance    0.192436  0.073467    1.000000  0.952015
Marks         0.146079 -0.114050    0.952015  1.000000

In [61]:
# Highest positive correlation
correlation = df.corr(numeric_only=True)

print("Highest Positive Correlation:")
print(correlation.stack().sort_values(ascending=False).iloc[1])

Highest Positive Correlation:
1.0

In [62]:
# Lowest correlation
print("Lowest Correlation:")
print(correlation.stack().sort_values().iloc[0])

Lowest Correlation:
-0.11404993013364456

In [63]:
# Gender Encoding
df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

# Purchased Encoding
df["Purchased"] = df["Purchased"].map({
    "Yes": 1,
    "No": 0
})

df

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,1,Pune,Python,90.000000,85.000000,1
1,102,Amit,22.000000,1,Mumbai,AI,80.000000,75.000000,0
2,103,Priya,20.000000,0,Nashik,Python,95.000000,92.000000,1
3,104,Sneha,23.000000,0,Pune,Data Science,88.000000,81.000000,1
4,105,Rahul,21.000000,1,Mumbai,AI,75.000000,65.000000,0
5,106,Pooja,22.000000,0,Pune,Python,98.000000,96.000000,1
6,107,Karan,20.000000,1,Nashik,Data Science,82.000000,79.000000,0
7,108,Neha,21.000000,0,Pune,AI,91.000000,89.000000,1
8,109,Akash,24.000000,1,Mumbai,Python,85.000000,72.000000,0
9,110,Komal,23.000000,0,Pune,Data Science,96.000000,94.000000,1
10,111,Vikas,21.666667,1,Pune,Python,90.000000,83.166667,1
11,112,Riya,22.000000,0,Mumbai,AI,88.333333,85.000000,0
12,113,Raj,21.000000,1,Pune,Python,90.000000,85.000000,1

In [64]:
# One-Hot Encoding for City and Course

df_encoded = pd.get_dummies(
    df,
    columns=["City", "Course"],
    dtype=int
)

df_encoded

,Student_ID,Name,Age,Gender,Attendance,Marks,Purchased,City_Mumbai,City_Nashik,City_Pune,Course_AI,Course_Data Science,Course_Python
0,101,Raj,21.000000,1,90.000000,85.000000,1,0,0,1,0,0,1
1,102,Amit,22.000000,1,80.000000,75.000000,0,1,0,0,1,0,0
2,103,Priya,20.000000,0,95.000000,92.000000,1,0,1,0,0,0,1
3,104,Sneha,23.000000,0,88.000000,81.000000,1,0,0,1,0,1,0
4,105,Rahul,21.000000,1,75.000000,65.000000,0,1,0,0,1,0,0
5,106,Pooja,22.000000,0,98.000000,96.000000,1,0,0,1,0,0,1
6,107,Karan,20.000000,1,82.000000,79.000000,0,0,1,0,0,1,0
7,108,Neha,21.000000,0,91.000000,89.000000,1,0,0,1,1,0,0
8,109,Akash,24.000000,1,85.000000,72.000000,0,1,0,0,0,0,1
9,110,Komal,23.000000,0,96.000000,94.000000,1,0,0,1,0,1,0
10,111,Vikas,21.666667,1,90.000000,83.166667,1,0,0,1,0,0,1
11,112,Riya,22.000000,0,88.333333,85.000000,0,1,0,0,1,0,0
12,113,Raj,21.000000,1,90.000000,85.000000,1,0,0,1,0,0,1

In [65]:
# Features
X = df[[
    "Age",
    "Attendance",
    "Marks",
    "Gender"
]]

# Target
y = df["Purchased"]

print("Features (X):")
print(X)

print("\nTarget (y):")
print(y)

Features (X):
          Age  Attendance      Marks  Gender
0   21.000000   90.000000  85.000000       1
1   22.000000   80.000000  75.000000       1
2   20.000000   95.000000  92.000000       0
3   23.000000   88.000000  81.000000       0
4   21.000000   75.000000  65.000000       1
5   22.000000   98.000000  96.000000       0
6   20.000000   82.000000  79.000000       1
7   21.000000   91.000000  89.000000       0
8   24.000000   85.000000  72.000000       1
9   23.000000   96.000000  94.000000       0
10  21.666667   90.000000  83.166667       1
11  22.000000   88.333333  85.000000       0
12  21.000000   90.000000  85.000000       1

Target (y):
0     1
1     0
2     1
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    1
11    0
12    1
Name: Purchased, dtype: int64

In [67]:
# Save cleaned dataset

df.to_csv("cleaned_student_performance.csv", index=False)

print("cleaned_student_performance.csv saved successfully!")

cleaned_student_performance.csv saved successfully!