23/06/2026

Assignment : 11

Pandas assignment : 2

Data Selection & Filtering

In [ ]:
# Pandas Training - Day 2 Assignment
# Topic: Data Selection & Filtering

import pandas as pd

# Create Employee DataFrame
data = {
    "Employee ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales"],
    "Salary": [45000, 35000, 55000, 40000, 60000],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Pune"]
}

df = pd.DataFrame(data)

# Display DataFrame
df

In [2]:
# 1. Display first 3 rows

df.head(3)

   Employee ID   Name Department  Salary    City
0          101  Rahul         IT   45000    Pune
1          102  Priya         HR   35000  Mumbai
2          103   Amit    Finance   55000    Pune

In [3]:
# 2. Display last 2 rows

df.tail(2)

   Employee ID   Name Department  Salary    City
3          104  Sneha         IT   40000  Nashik
4          105  Rohan      Sales   60000    Pune

In [4]:
# 3. Display dataset shape

df.shape

(5, 5)

In [5]:
# 4. Display column names

df.columns

Index(['Employee ID', 'Name', 'Department', 'Salary', 'City'], dtype='object')

In [6]:
# 5. Display employees whose salary is greater than 40000

df[df["Salary"] > 40000]

   Employee ID   Name Department  Salary  City
0          101  Rahul         IT   45000  Pune
2          103   Amit    Finance   55000  Pune
4          105  Rohan      Sales   60000  Pune

In [7]:
# 6. Display employees from Pune

df[df["City"] == "Pune"]

   Employee ID   Name Department  Salary  City
0          101  Rahul         IT   45000  Pune
2          103   Amit    Finance   55000  Pune
4          105  Rohan      Sales   60000  Pune

Questions

Q1. What is the purpose of head()?

head() is used to display the first rows of a DataFrame. By default, it displays the first 5 rows.

Q2. What is the purpose of tail()?

tail() is used to display the last rows of a DataFrame. By default, it displays the last 5 rows.

Q3. What does shape return?

shape returns the number of rows and columns in a DataFrame.

In [9]:
#Example:

df.shape

(5, 5)

In [ ]:
Q4. What does info() display?

info() displays information about the DataFrame, such as:

Number of rows
Column names
Data types
Non-null values
Memory usage

In [11]:
#Example

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Department   5 non-null      object
 3   Salary       5 non-null      int64
 4   City         5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

Q5. What does describe() display?

describe() displays statistical information about numerical columns, such as:

Count
Mean
Standard deviation
Minimum
Maximum

In [14]:
#Example:

df.describe()

       Employee ID        Salary
count     5.000000      5.000000
mean    103.000000  47000.000000
std       1.581139  10368.220677
min     101.000000  35000.000000
25%     102.000000  40000.000000
50%     103.000000  45000.000000
75%     104.000000  55000.000000
max     105.000000  60000.000000

Q6. Write a program to display employees whose salary is greater than 50000.

In [15]:

df[df["Salary"] > 50000]

   Employee ID   Name Department  Salary  City
2          103   Amit    Finance   55000  Pune
4          105  Rohan      Sales   60000  Pune