26/06/2026

Assignment : 13

Pandas assignment : 4

Sorting & Grouping

In [1]:
# Pandas Training - Day 4 Assignment
# Topics: Sorting & Grouping

import pandas as pd

# Create Employee DataFrame

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Salary": [45000, 35000, 55000, 40000, 50000, 60000]
}

df = pd.DataFrame(data)

# Display DataFrame
df

    Name Department  Salary
0  Rahul         IT   45000
1  Priya         HR   35000
2   Amit         IT   55000
3  Sneha    Finance   40000
4  Rohan         HR   50000
5   Neha    Finance   60000

In [2]:
# Sort salary in ascending order

df.sort_values("Salary", ascending=True)

    Name Department  Salary
1  Priya         HR   35000
3  Sneha    Finance   40000
0  Rahul         IT   45000
4  Rohan         HR   50000
2   Amit         IT   55000
5   Neha    Finance   60000

In [3]:
# Sort salary in descending order

df.sort_values("Salary", ascending=False)

    Name Department  Salary
5   Neha    Finance   60000
2   Amit         IT   55000
4  Rohan         HR   50000
0  Rahul         IT   45000
3  Sneha    Finance   40000
1  Priya         HR   35000

In [4]:
# Display unique departments

df["Department"].unique()

array(['IT', 'HR', 'Finance'], dtype=object)

In [5]:
# Count employees in each department

df["Department"].value_counts()

Department
IT         2
HR         2
Finance    2
Name: count, dtype: int64

In [6]:
# Find average salary of each department

df.groupby("Department")["Salary"].mean()

Department
Finance    50000.0
HR         42500.0
IT         50000.0
Name: Salary, dtype: float64

In [7]:
# Find maximum salary of each department

df.groupby("Department")["Salary"].max()

Department
Finance    60000
HR         50000
IT         55000
Name: Salary, dtype: int64

Questions

Q1. What is the purpose of sort_values()?

sort_values() is used to sort the data in a DataFrame based on one or more columns.

In [8]:
#Example:

df.sort_values("Salary")

    Name Department  Salary
1  Priya         HR   35000
3  Sneha    Finance   40000
0  Rahul         IT   45000
4  Rohan         HR   50000
2   Amit         IT   55000
5   Neha    Finance   60000

Q2. What is the difference between ascending and descending sorting?
Ascending: Data is arranged from smallest to largest.
Descending: Data is arranged from largest to smallest.

In [9]:
#Example:

# Ascending
df.sort_values("Salary", ascending=True)


# Descending
df.sort_values("Salary", ascending=False)

    Name Department  Salary
5   Neha    Finance   60000
2   Amit         IT   55000
4  Rohan         HR   50000
0  Rahul         IT   45000
3  Sneha    Finance   40000
1  Priya         HR   35000

Q3. What is the purpose of unique()?

unique() is used to find the unique values in a column.

In [10]:
#Example:

df["Department"].unique()

array(['IT', 'HR', 'Finance'], dtype=object)

Q4. What is the purpose of value_counts()?

value_counts() is used to count how many times each unique value appears in a column.

In [12]:
#Example:

df["Department"].value_counts()

Department
IT         2
HR         2
Finance    2
Name: count, dtype: int64

Q5. What is groupby()?

groupby() is used to group data based on one or more columns and perform calculations on each group.

In [14]:
#Example:

df.groupby("Department")["Salary"].mean()

Department
Finance    50000.0
HR         42500.0
IT         50000.0
Name: Salary, dtype: float64

Q6. Write the aggregation functions available in Pandas.

Common aggregation functions in Pandas are:

sum() – calculates total
mean() – calculates average
min() – finds minimum value
max() – finds maximum value
count() – counts values
median() – finds middle value
std() – calculates standard deviation
var() – calculates variance

In [16]:
#Example:

df.groupby("Department")["Salary"].agg(["sum", "mean", "min", "max", "count"])

               sum     mean    min    max  count
Department
Finance     100000  50000.0  40000  60000      2
HR           85000  42500.0  35000  50000      2
IT          100000  50000.0  45000  55000      2