24/06/2026

Assignment : 12

Pandas assignment : 3

Data Cleaning

In [1]:
# Pandas Training - Day 3 Assignment
# Topic: Data Cleaning

import pandas as pd

# Create Student DataFrame with missing values and one duplicate record

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Priya"],
    "Age": [20, None, 21, None, None],
    "Marks": [85, 90, None, 78, 90]
}

df = pd.DataFrame(data)

# Display DataFrame
df

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya   NaN   90.0
2   Amit  21.0    NaN
3  Sneha   NaN   78.0
4  Priya   NaN   90.0

In [2]:
# Find missing values

df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4  False   True  False

In [3]:
# Count missing values in each column

df.isnull().sum()

Name     0
Age      3
Marks    1
dtype: int64

In [4]:
# Replace all missing values with 0

df_zero = df.fillna(0)

df_zero

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya   0.0   90.0
2   Amit  21.0    0.0
3  Sneha   0.0   78.0
4  Priya   0.0   90.0

In [5]:
# Calculate average age

average_age = df["Age"].mean()

# Replace missing age with average age

df["Age"] = df["Age"].fillna(average_age)

df

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  20.5   90.0
2   Amit  21.0    NaN
3  Sneha  20.5   78.0
4  Priya  20.5   90.0

In [6]:
# Identify duplicate records

df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [7]:
# Remove duplicate records

df = df.drop_duplicates()

df

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  20.5   90.0
2   Amit  21.0    NaN
3  Sneha  20.5   78.0

Questions

Q1. What is Data Cleaning?

Data Cleaning is the process of finding and correcting or removing incorrect, missing, duplicate, or unwanted data from a dataset.

Q2. What is a Missing Value?

A Missing Value is a value that is not available or not entered in a dataset. In Pandas, it is usually represented as NaN.

Q3. What is the purpose of isnull()?

isnull() is used to find missing values in a DataFrame. It returns True where a value is missing and False where a value is present.

In [8]:
#Example:

df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False   True
3  False  False  False

Q4. What is the purpose of fillna()?

fillna() is used to replace missing values with a specified value or another calculated value.

In [12]:
#Example:

df.fillna(0)

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  20.5   90.0
2   Amit  21.0    0.0
3  Sneha  20.5   78.0

Q5. What is the difference between fillna() and dropna()?
fillna() replaces missing values.
dropna() removes rows or columns containing missing values.

In [14]:
#Example:

df.fillna(0)
df.dropna()

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  20.5   90.0
3  Sneha  20.5   78.0

Q6. What is the purpose of drop_duplicates()?

drop_duplicates() is used to remove duplicate rows from a DataFrame.

In [16]:
#Example:

df.drop_duplicates()

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Priya  20.5   90.0
2   Amit  21.0    NaN
3  Sneha  20.5   78.0